import { Router } from "express";
import UserRouter from "./user";
import AuthRouter from "./auth";
import ProductRouter from "./product";
import OfferRouter from "./offer";
import MediaRouter from "./media";
import AdminRouter from "./admin";
import CategoryRouter from "./category";
import OrderRouter from "./order";
import DeliveryLocationRouter from "./deliveryLocation";
import PaymentRouter from "./payment";
let router = Router();

router.use("/auth", AuthRouter);
router.use("/deliverylocations", DeliveryLocationRouter);
router.use("/admin", AdminRouter);
router.use("/user", UserRouter);
router.use("/media", MediaRouter);
router.use("/product", ProductRouter);
router.use("/offer", OfferRouter);
router.use("/category", CategoryRouter);
router.use("/orders", OrderRouter);
router.use("/payment", PaymentRouter);
router.get("*", (req, res) => res.send("Invalid requist , Page not found 404"));
export default router;
